"""add_medications_tables

Revision ID: 518f6ce854cd
Revises: 2811e9c6c9d4
Create Date: 2026-02-10 08:25:00.430172
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '518f6ce854cd'
down_revision: Union[str, None] = '2811e9c6c9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('atc_code', sa.String(length=10), nullable=True),
    sa.Column('dose', sa.String(length=50), nullable=False),
    sa.Column('dose_unit', sa.String(length=20), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prescribed_by', sa.UUID(), nullable=True),
    sa.Column('is_prn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('medication_administrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('administered_by', sa.UUID(), nullable=True),
    sa.Column('dose_given', sa.String(length=50), nullable=False),
    sa.Column('dose_unit', sa.String(length=20), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason_not_given', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_medication_id'), 'medication_administrations', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_patient_id'), 'medication_administrations', ['patient_id'], unique=False)
    # Note: vital_signs FK and hypertable index intentionally skipped (TimescaleDB Hypertable)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_administrations_patient_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_medication_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
