"""phase_3b_home_spital_features

Revision ID: 792a43a9750b
Revises: a11d04c11d4d
Create Date: 2026-02-10 13:09:38.424513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '792a43a9750b'
down_revision: Union[str, None] = 'a11d04c11d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('last_reading_value', sa.String(length=50), nullable=True),
    sa.Column('last_reading_unit', sa.String(length=20), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_threshold_low', sa.String(length=50), nullable=True),
    sa.Column('alert_threshold_high', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_devices_patient_id'), 'remote_devices', ['patient_id'], unique=False)
    op.create_table('home_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('assigned_nurse_id', sa.UUID(), nullable=True),
    sa.Column('assigned_nurse_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('visit_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('vital_signs_recorded', sa.Boolean(), nullable=False),
    sa.Column('medication_administered', sa.Boolean(), nullable=False),
    sa.Column('wound_care_performed', sa.Boolean(), nullable=False),
    sa.Column('iv_therapy_performed', sa.Boolean(), nullable=False),
    sa.Column('blood_drawn', sa.Boolean(), nullable=False),
    sa.Column('patient_condition', sa.String(length=20), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_visits_patient_id'), 'home_visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_home_visits_planned_date'), 'home_visits', ['planned_date'], unique=False)
    op.create_table('self_medication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_medication_logs_medication_id'), 'self_medication_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_self_medication_logs_patient_id'), 'self_medication_logs', ['patient_id'], unique=False)
    op.create_table('teleconsults',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('physician_id', sa.UUID(), nullable=True),
    sa.Column('physician_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('meeting_platform', sa.String(length=50), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('soap_subjective', sa.Text(), nullable=True),
    sa.Column('soap_objective', sa.Text(), nullable=True),
    sa.Column('soap_assessment', sa.Text(), nullable=True),
    sa.Column('soap_plan', sa.Text(), nullable=True),
    sa.Column('technical_quality', sa.String(length=10), nullable=True),
    sa.Column('followup_required', sa.Boolean(), nullable=False),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('clinical_note_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teleconsults_patient_id'), 'teleconsults', ['patient_id'], unique=False)
    # Removed: vital_signs FK, clinical_notes index drops, vital_signs index drop (TimescaleDB)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: vital_signs index recreate, clinical_notes index recreates, alarms FK drop (TimescaleDB)
    op.drop_index(op.f('ix_teleconsults_patient_id'), table_name='teleconsults')
    op.drop_table('teleconsults')
    op.drop_index(op.f('ix_self_medication_logs_patient_id'), table_name='self_medication_logs')
    op.drop_index(op.f('ix_self_medication_logs_medication_id'), table_name='self_medication_logs')
    op.drop_table('self_medication_logs')
    op.drop_index(op.f('ix_home_visits_planned_date'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_patient_id'), table_name='home_visits')
    op.drop_table('home_visits')
    op.drop_index(op.f('ix_remote_devices_patient_id'), table_name='remote_devices')
    op.drop_table('remote_devices')
    # ### end Alembic commands ###
