"""phase_3a_planning_legal_stammdaten

Revision ID: a11d04c11d4d
Revises: a3c7f1d82e45
Create Date: 2026-02-10 11:36:41.004613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a11d04c11d4d'
down_revision: Union[str, None] = 'a3c7f1d82e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=200), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('witness_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('medical_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hin_email', sa.String(length=255), nullable=True),
    sa.Column('gln_number', sa.String(length=13), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('speciality', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_providers_patient_id'), 'medical_providers', ['patient_id'], unique=False)
    op.create_table('palliative_care',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('reserve_morphin', sa.String(length=100), nullable=True),
    sa.Column('reserve_midazolam', sa.String(length=100), nullable=True),
    sa.Column('reserve_haloperidol', sa.String(length=100), nullable=True),
    sa.Column('reserve_scopolamin', sa.String(length=100), nullable=True),
    sa.Column('reserve_other', sa.Text(), nullable=True),
    sa.Column('palliative_service_name', sa.String(length=255), nullable=True),
    sa.Column('palliative_service_phone', sa.String(length=20), nullable=True),
    sa.Column('palliative_service_email', sa.String(length=255), nullable=True),
    sa.Column('goals_of_care', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_palliative_care_patient_id'), 'palliative_care', ['patient_id'], unique=True)
    op.create_table('advance_directives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('directive_type', sa.String(length=30), nullable=False),
    sa.Column('rea_status', sa.String(length=10), nullable=False),
    sa.Column('intensive_care', sa.Boolean(), nullable=False),
    sa.Column('mechanical_ventilation', sa.Boolean(), nullable=False),
    sa.Column('dialysis', sa.Boolean(), nullable=False),
    sa.Column('artificial_nutrition', sa.Boolean(), nullable=False),
    sa.Column('trusted_person_name', sa.String(length=200), nullable=True),
    sa.Column('trusted_person_phone', sa.String(length=20), nullable=True),
    sa.Column('trusted_person_relation', sa.String(length=50), nullable=True),
    sa.Column('trusted_person_contact_id', sa.UUID(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['trusted_person_contact_id'], ['emergency_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_directives_patient_id'), 'advance_directives', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=30), nullable=True),
    sa.Column('recurrence_end', sa.Date(), nullable=True),
    sa.Column('parent_appointment_id', sa.UUID(), nullable=True),
    sa.Column('transport_required', sa.Boolean(), nullable=False),
    sa.Column('transport_type', sa.String(length=30), nullable=True),
    sa.Column('transport_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['parent_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_table('death_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_role', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emergency_contact_id'], ['emergency_contacts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_death_notifications_patient_id'), 'death_notifications', ['patient_id'], unique=False)
    op.create_table('discharge_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('planned_discharge_date', sa.Date(), nullable=True),
    sa.Column('actual_discharge_date', sa.Date(), nullable=True),
    sa.Column('crp_declining', sa.Boolean(), nullable=False),
    sa.Column('crp_below_50', sa.Boolean(), nullable=False),
    sa.Column('afebrile_48h', sa.Boolean(), nullable=False),
    sa.Column('oral_stable_48h', sa.Boolean(), nullable=False),
    sa.Column('clinical_improvement', sa.Boolean(), nullable=False),
    sa.Column('aftercare_organized', sa.Boolean(), nullable=False),
    sa.Column('followup_gp', sa.String(length=255), nullable=True),
    sa.Column('followup_gp_date', sa.Date(), nullable=True),
    sa.Column('followup_spitex', sa.String(length=255), nullable=True),
    sa.Column('followup_spitex_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_criteria_patient_id'), 'discharge_criteria', ['patient_id'], unique=True)
    op.create_table('patient_wishes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('quality_of_life', sa.Text(), nullable=True),
    sa.Column('autonomy_preferences', sa.Text(), nullable=True),
    sa.Column('pain_management', sa.Text(), nullable=True),
    sa.Column('decision_maker', sa.String(length=200), nullable=True),
    sa.Column('decision_maker_contact_id', sa.UUID(), nullable=True),
    sa.Column('sleep_preferences', sa.Text(), nullable=True),
    sa.Column('nutrition_preferences', sa.Text(), nullable=True),
    sa.Column('family_wishes', sa.Text(), nullable=True),
    sa.Column('pet_info', sa.Text(), nullable=True),
    sa.Column('spiritual_needs', sa.Text(), nullable=True),
    sa.Column('other_wishes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_maker_contact_id'], ['emergency_contacts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_wishes_patient_id'), 'patient_wishes', ['patient_id'], unique=True)
    # Removed: FK to vital_signs hypertable not supported
    # Removed: clinical_notes index drops (stay as-is)
    op.add_column('emergency_contacts', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('emergency_contacts', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('emergency_contacts', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('emergency_contacts', sa.Column('is_legal_representative', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('emergency_contacts', sa.Column('is_key_person', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('emergency_contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('insurances', sa.Column('franchise', sa.Integer(), nullable=True))
    op.add_column('insurances', sa.Column('kostengutsprache', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('insurances', sa.Column('kostengutsprache_bis', sa.Date(), nullable=True))
    op.add_column('insurances', sa.Column('garant', sa.String(length=30), nullable=True))
    op.add_column('insurances', sa.Column('bvg_number', sa.String(length=50), nullable=True))
    op.add_column('insurances', sa.Column('notes', sa.Text(), nullable=True))
    # Removed: vital_signs hypertable index drop
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: vital_signs hypertable index recreation
    op.drop_column('insurances', 'notes')
    op.drop_column('insurances', 'bvg_number')
    op.drop_column('insurances', 'garant')
    op.drop_column('insurances', 'kostengutsprache_bis')
    op.drop_column('insurances', 'kostengutsprache')
    op.drop_column('insurances', 'franchise')
    op.drop_column('emergency_contacts', 'notes')
    op.drop_column('emergency_contacts', 'is_key_person')
    op.drop_column('emergency_contacts', 'is_legal_representative')
    op.drop_column('emergency_contacts', 'priority')
    op.drop_column('emergency_contacts', 'address')
    op.drop_column('emergency_contacts', 'email')
    # Removed: clinical_notes index recreation + alarms FK drop
    op.drop_index(op.f('ix_patient_wishes_patient_id'), table_name='patient_wishes')
    op.drop_table('patient_wishes')
    op.drop_index(op.f('ix_discharge_criteria_patient_id'), table_name='discharge_criteria')
    op.drop_table('discharge_criteria')
    op.drop_index(op.f('ix_death_notifications_patient_id'), table_name='death_notifications')
    op.drop_table('death_notifications')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_advance_directives_patient_id'), table_name='advance_directives')
    op.drop_table('advance_directives')
    op.drop_index(op.f('ix_palliative_care_patient_id'), table_name='palliative_care')
    op.drop_table('palliative_care')
    op.drop_index(op.f('ix_medical_providers_patient_id'), table_name='medical_providers')
    op.drop_table('medical_providers')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
